#Mon Jul 19 08:25:17 UTC 2021
version=1.2.5-SNAPSHOT
systemProp.file.encoding=utf-8
timebaseVersion=6.2.11
commonsVersion=6.0.68
springBootVersion=3.4.3
springVersion=6.2.3
springSecurityVersion=6.4.3
tomcatVersion=10.1.39
jacksonVersion=2.18.2
nettyVersion=4.1.119.Final
group=com.epam.deltix
docker.dockerCommonPath=epam/