export declare const darkCryptoCortexColors: {
    green: number;
    green2: number;
    pink: number;
    pink2: number;
    pink3: number;
    black: number;
    black1: number;
    white: number;
    grey: number;
    grey2: number;
    grey3: number;
    blue: number;
    blue2: number;
    blue3: number;
    blue4: number;
    blue5: number;
    blue6: number;
    blue7: number;
    blue8: number;
    blue9: number;
    gradient: number;
};
export declare const whiteCryptoCortexColors: {
    green: number;
    green2: number;
    pink: number;
    black: number;
    hover: number;
    blue: number;
    blue1: number;
    blue2: number;
    blue3: number;
    blue4: number;
    blue5: number;
    blue6: number;
    blue7: number;
    white: number;
    white2: number;
    white3: number;
    grey: number;
    grey1: number;
    grey2: number;
    grey3: number;
};
