export const dateTimeFormats = [
  "dd-MM-yyyy'T'HH:mm:ss'Z'",
  "yyyy-MM-dd'T'HH:mm:ss'Z'",
  "MM/dd/yyyy'T'HH:mm:ss'Z'",
  "yyyy/MM/dd'T'HH:mm:ss'Z'",
  "dd MMM yyyy'T'HH:mm:ss'Z'",
  "dd MMMM yyyy'T'HH:mm:ss'Z'",
  "dd-MM-yyyy HH:mm:ss",
  "yyyy-MM-dd HH:mm:ss",
  "MM/dd/yyyy HH:mm:ss",
  "yyyy/MM/dd HH:mm:ss",
  "dd MMM yyyy HH:mm:ss",
  "dd MMMM yyyy HH:mm:ss",
  "dd-MM-yyyy'T'HH:mm:ss.SSS'Z'",
  "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
  "MM/dd/yyyy'T'HH:mm:ss.SSS'Z'",
  "yyyy/MM/dd'T'HH:mm:ss.SSS'Z'",
  "dd MMM yyyy'T'HH:mm:ss.SSS'Z'",
  "dd MMMM yyyy'T'HH:mm:ss.SSS'Z'",
  "dd-MM-yyyy'T'HH:mm:ss",
  "yyyy-MM-dd'T'HH:mm:ss",
  "MM/dd/yyyy'T'HH:mm:ss",
  "yyyy/MM/dd'T'HH:mm:ss",
  "dd MMM yyyy'T'HH:mm:ss",
  "dd MMMM yyyy'T'HH:mm:ss",
  "dd-MM-yyyy'T'HH:mm:ss.SSS",
  "yyyy-MM-dd'T'HH:mm:ss.SSS",
  "MM/dd/yyyy'T'HH:mm:ss.SSS",
  "yyyy/MM/dd'T'HH:mm:ss.SSS",
  "dd MMM yyyy'T'HH:mm:ss.SSS",
  "dd MMMM yyyy'T'HH:mm:ss.SSS",
  "dd-MM-yyyy HH:mm",
  "yyyy-MM-dd HH:mm",
  "MM/dd/yyyy HH:mm",
  "yyyy/MM/dd HH:mm",
  "dd MMM yyyy HH:mm",
  "dd MMMM yyyy HH:mm",
  "yyyyMMddHHmmss",
  "yyyyMMdd HHmmss",
  "dd-MM-yyyy HH:mm:ss.SSS",
  "yyyy-MM-dd HH:mm:ss.SSS",
  "MM/dd/yyyy HH:mm:ss.SSS",
  "yyyy/MM/dd HH:mm:ss.SSS",
  "dd MMM yyyy HH:mm:ss.SSS",
  "dd MMMM yyyy HH:mm:ss.SSS",
  "dd-MM-yyyy HH:mm:ss Z",
  "yyyy-MM-dd HH:mm:ss Z",
  "MM/dd/yyyy HH:mm:ss Z",
  "yyyy/MM/dd HH:mm:ss Z",
  "dd MMM yyyy HH:mm:ss Z",
  "dd MMMM yyyy HH:mm:ss Z",
  "dd-MM-yyyy HH:mm:ss Z",
  "yyyy-MM-dd HH:mm:ss Z",
  "MM/dd/yyyy HH:mm:ss Z",
  "yyyy/MM/dd HH:mm:ss Z",
  "dd MMM yyyy HH:mm:ss Z",
  "dd MMMM yyyy HH:mm:ss Z",
  "dd-MM-yyyy'T'HH:mm:ss'Z'Z",
  "yyyy-MM-dd'T'HH:mm:ss'Z'Z",
  "MM/dd/yyyy'T'HH:mm:ss'Z'Z",
  "yyyy/MM/dd'T'HH:mm:ss'Z'Z",
  "dd MMM yyyy'T'HH:mm:ss'Z'Z",
  "dd MMMM yyyy'T'HH:mm:ss'Z'Z",
  "dd-MM-yyyy'T'HH:mm:ss.SSS'Z'Z",
  "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'Z",
  "MM/dd/yyyy'T'HH:mm:ss.SSS'Z'Z",
  "yyyy/MM/dd'T'HH:mm:ss.SSS'Z'Z",
  "dd MMM yyyy'T'HH:mm:ss.SSS'Z'Z",
  "dd MMMM yyyy'T'HH:mm:ss.SSS'Z'Z",
];